.\" Manpage for kreator_kopii_180194
.\" Contact to correct typos/errors
.TH kreator_kopii_180194 7 "31 MAY 2020" Linux "User manuals"
.SH NAME
kreator_kopii_180194 \- create a backup copy of your files.
.SH SYNOPSIS
kreator_kopii_180194.sh [-h] [-v]
.SH DESCRIPTION
.B kreator_kopii_180194 
is a program, operated through zenity, that helps the user to make a backup copy of files. The user chooses files in 
.I wybierz pliki do archiwizacji
option and directories in
.I wybierz katalogi do archiwizacji
option. The user could also exclude files with chosen extensions by
.I wybierz rozszerzenia do odfiltrowania
option. The program also archivises the previous backup copy. User can choose the type of archiving in
.I wybierz rodzaj archwizacji poprzedniej kopii
option. Settings can be exported to a file and imported from a file. To create a copy, click on
.B Stworz kopie zapasowa 
option.
.SH OPTIONS
.IP -h
- shows help message 
.IP -v
- shows the version of the program 
.SH BUGS
No known bugs.
.SH AUTHOR
Written by: Kamil Paluszewski (s180194@student.pg.edu.pl)
.SH REPORTING BUGS
s180194@student.pg.edu.pl

